### ISSUE TITLE
QR is displayed in both the payment method

### ISSUE THREAD

**Issue by GrishnaVaidya** [radhikaneupane/Restaurant-Management-System#7]
In the cahier dashboard, QR code is displayed even when the user choose cash as the payment method i.e. QR code is displayed in both of the payment method. QR should be displayed only in e-Sewa not in both payment method.

**Comment by AnjanaYadav12** [comment]
Radhika Might be Up on this task

**Comment by radhikaneupane** [comment]
Completed
